// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY3w-R_1jvCEUzutjXfkXJTilLGRCH5dI',
    appId: '1:433757665464:web:81332497620c12f2fedc4d',
    messagingSenderId: '433757665464',
    projectId: 'flutterproject-95c53',
    authDomain: 'flutterproject-95c53.firebaseapp.com',
    storageBucket: 'flutterproject-95c53.firebasestorage.app',
    measurementId: 'G-QY1DRYSV6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFjLA62M7lc7v_armRboupkx7Fn0a6J0Y',
    appId: '1:433757665464:android:7b3d7ffaa700a8b5fedc4d',
    messagingSenderId: '433757665464',
    projectId: 'flutterproject-95c53',
    storageBucket: 'flutterproject-95c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF45bU14Kk-4oyjUSYfgUDgTJIpDbdh6k',
    appId: '1:433757665464:ios:d3dd094330b8370bfedc4d',
    messagingSenderId: '433757665464',
    projectId: 'flutterproject-95c53',
    storageBucket: 'flutterproject-95c53.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF45bU14Kk-4oyjUSYfgUDgTJIpDbdh6k',
    appId: '1:433757665464:ios:d3dd094330b8370bfedc4d',
    messagingSenderId: '433757665464',
    projectId: 'flutterproject-95c53',
    storageBucket: 'flutterproject-95c53.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY3w-R_1jvCEUzutjXfkXJTilLGRCH5dI',
    appId: '1:433757665464:web:800a6d695ae4f6aefedc4d',
    messagingSenderId: '433757665464',
    projectId: 'flutterproject-95c53',
    authDomain: 'flutterproject-95c53.firebaseapp.com',
    storageBucket: 'flutterproject-95c53.firebasestorage.app',
    measurementId: 'G-MXGQFB7DNE',
  );
}
